name: Build and Deploy Node.js Docker App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

   
    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository }}/my-node-app:latest .

    - name: Run container for testing
      run: |
        docker run -d -p 3000:3000 --name test-app ghcr.io/${{ github.repository }}/my-node-app:latest
        sleep 5
        curl --fail http://localhost:3000

    - name: Stop test container
      run: docker rm -f test-app


    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository }}/my-node-app:latest
